// Curated table-of-contents outlines per script. The dialogue data has no scene
// or "importance" metadata, so scene headers and the major branch decisions are
// listed here in story order. Entries whose nodeId isn't present in the loaded
// graph are skipped, so partial/renamed scripts degrade gracefully.

export interface TocEntry {
  title: string;
  nodeId: string;
  kind: "scene" | "decision";
}

export const TOC: Record<string, TocEntry[]> = {
    "lifeisstrange/episode1": [
        {title: "Jefferson's Class", nodeId: "start", kind: "scene"},
        {title: "Hallway & Principal Wells", nodeId: "david_hallway", kind: "scene"},
        {title: "Report Nathan?", nodeId: "wells_1", kind: "decision"},
        {title: "Make fun of Victoria?", nodeId: "victoria_1", kind: "decision"},
        {title: "Dorm: Juliet", nodeId: "juliet_1", kind: "scene"},
        {title: "Photograph Kate?", nodeId: "kate_1", kind: "decision"},
        {title: "Warren", nodeId: "warren_1", kind: "scene"},
        {title: "Nathan Confrontation", nodeId: "nathan_1", kind: "scene"},
        {title: "Chloe's House", nodeId: "chloe_1", kind: "scene"},
        {title: "David & Chloe", nodeId: "david_hide", kind: "scene"},
        {title: "Blame Chloe or take the blame?", nodeId: "david_exposed", kind: "decision"},
        {title: "Lighthouse (ending)", nodeId: "lighthouse_2", kind: "scene"},
    ],
    "lifeisstrange/episode2": [
        {title: "Girls' Dormitories", nodeId: "maxroom_intro", kind: "scene"},
        {title: "Showers", nodeId: "showers_1", kind: "scene"},
        {title: "Kate's Room", nodeId: "kateroom_1", kind: "scene"},
        {title: "Police or find proof?", nodeId: "kateroom_13", kind: "decision"},
        {title: "Dormitories: Warren", nodeId: "dorm_warren_1", kind: "scene"},
        {title: "Two Whales Diner", nodeId: "diner_bridge", kind: "scene"},
        {title: "American Rust Junkyard", nodeId: "junkyard_1", kind: "scene"},
        {title: "Railroad", nodeId: "railroad_1", kind: "scene"},
        {title: "Main Campus", nodeId: "campus_1", kind: "scene"},
        {title: "Hallway: David", nodeId: "david_1", kind: "scene"},
        {title: "Science Lab", nodeId: "sciencelab_1", kind: "scene"},
        {title: "Jefferson's Class", nodeId: "jeff_1", kind: "scene"},
        {title: "Kate on the Roof", nodeId: "dorm2_bridge", kind: "scene"},
        {title: "Talk Kate down?", nodeId: "roof_1", kind: "decision"},
        {title: "Principal's Office", nodeId: "principal_1", kind: "scene"},
        {title: "Who to blame?", nodeId: "principal_3", kind: "decision"},
        {title: "With Warren", nodeId: "warren_end_1", kind: "scene"},
        {title: "Epilogue", nodeId: "epilogue", kind: "scene"},
    ],
    "lifeisstrange/episode3": [
        {title: "Dorm at Night", nodeId: "dorm_maxroom", kind: "scene"},
        {title: "Sneak Past Wells", nodeId: "wells", kind: "scene"},
        {title: "Main Campus", nodeId: "campus_1", kind: "scene"},
        {title: "Break-in", nodeId: "hallway2_1", kind: "scene"},
        {title: "Principal's Office", nodeId: "office", kind: "scene"},
        {title: "Swimming Pool", nodeId: "pool_1", kind: "scene"},
        {title: "Chloe's Room", nodeId: "upstairs", kind: "scene"},
        {title: "Breakfast with Joyce", nodeId: "downstairs_1", kind: "scene"},
        {title: "Diner: Frank", nodeId: "diner_frank1", kind: "scene"},
        {title: "Frank's RV", nodeId: "rv_1", kind: "scene"},
        {title: "Give Chloe the gun?", nodeId: "rv_gun", kind: "decision"},
        {title: "Chloe's Truck", nodeId: "truck_1_intro", kind: "scene"},
        {title: "The Photo (2008)", nodeId: "maxroom2", kind: "scene"},
        {title: "Save William?", nodeId: "focus_keys", kind: "decision"},
        {title: "Epilogue", nodeId: "epilogue", kind: "scene"},
    ],
    "lifeisstrange/episode4": [
        {title: "Alternate Timeline: Beach", nodeId: "alt_beach_intro", kind: "scene"},
        {title: "Alternate Chloe's Room", nodeId: "alt_room_1", kind: "scene"},
        {title: "Euthanize Chloe?", nodeId: "alt_euthanasia", kind: "decision"},
        {title: "2008 (undo it)", nodeId: "alt_2008", kind: "scene"},
        {title: "Back to Reality", nodeId: "real_room_1", kind: "scene"},
        {title: "David's Garage", nodeId: "garage", kind: "scene"},
        {title: "Hospital (Kate)", nodeId: "hospital", kind: "scene"},
        {title: "Dormitories", nodeId: "dorm_intro", kind: "scene"},
        {title: "Nathan's Room", nodeId: "nathan_room", kind: "scene"},
        {title: "Warren vs Nathan", nodeId: "hallway_warren_choice", kind: "decision"},
        {title: "Beach: Frank", nodeId: "beach_1", kind: "scene"},
        {title: "Frank's outcome", nodeId: "beach_outcome", kind: "decision"},
        {title: "Investigation", nodeId: "invest_1", kind: "scene"},
        {title: "Old Barn (Dark Room)", nodeId: "barn_1", kind: "scene"},
        {title: "Junkyard: Rachel", nodeId: "junkyard_grave", kind: "scene"},
        {title: "Parking Lot", nodeId: "parking_1", kind: "scene"},
        {title: "The Party", nodeId: "party_stella", kind: "scene"},
        {title: "Warn Victoria?", nodeId: "party_vic_warn", kind: "decision"},
        {title: "\"Everyday Heroes\" Contest", nodeId: "contest", kind: "scene"},
        {title: "Junkyard (ending)", nodeId: "junkyard_evening", kind: "scene"},
    ],
    "lifeisstrange/episode5": [
        {title: "First Focus (Dark Room)", nodeId: "focus1_intro", kind: "scene"},
        {title: "Second Focus", nodeId: "focus2_1", kind: "scene"},
        {title: "Photography Lab (Monday)", nodeId: "photolab_class", kind: "scene"},
        {title: "San Francisco Gallery", nodeId: "gallery", kind: "scene"},
        {title: "Dark Room (again)", nodeId: "darkroom_back", kind: "scene"},
        {title: "David rescue", nodeId: "darkroom_weapon", kind: "decision"},
        {title: "Conversation with David", nodeId: "david_1", kind: "scene"},
        {title: "Tell David the truth?", nodeId: "david_truth", kind: "decision"},
        {title: "Conversation with Warren", nodeId: "warren_1", kind: "scene"},
        {title: "Parking Lot (stop Chloe)", nodeId: "parking_1", kind: "scene"},
        {title: "Beach", nodeId: "beach", kind: "scene"},
        {title: "Nightmare", nodeId: "nightmare_photolab", kind: "scene"},
        {title: "Alternate Max", nodeId: "altmax_1", kind: "scene"},
        {title: "The Cliff", nodeId: "cliff", kind: "scene"},
        {title: "Sacrifice Chloe or the Bay?", nodeId: "final_choice", kind: "decision"},
    ],
};
